### ISSUE TITLE
Cardinality of features in MNIST and Embedding Generator

### ISSUE THREAD

**Issue by mortezamg63** [sajaddarabi/ContrastiveMixup#2]
You change the mnist images to vector (784D). Do you consider each element in the vector as a categorical column with cardinality number 256? Is my understanding correct?
 Here you do not use embedding layer for mnist dataset. What about other datasets? Do you use embedding layer for other datasets? if so, how do set parameters for embedding layers (cat_idxs, cat_dims)?

**Comment by sajaddarabi** [comment]
The MNIST images are flattened to 784 dimensional vectors (28 * 28). Each element in the vector is treated as a continuous value, there are no embeddings for MNIST as they aren't categorical features.

Embeddings are introduced for categorical features in tabular data. By default the embedding generator uses a heuristic to compute the embedding size for each categorical column: 

https://github.com/sajaddarabi/ContrastiveMixup/blob/b3a8ec12cb04f604a30017a960387e33e3b4dabe/model/nn_utils.py#L75 

You could also pass in your own desired embedding size.

**Comment by sajaddarabi** [comment]
Hi Morteza,

The MNIST images are flattened to 784 dimensional vectors (28 * 28). Each element in the vector is treated as a continuous value, and there are no embeddings for MNIST as they aren't categorical features.

Embeddings are introduced for categorical features in tabular data. By default the embedding generator uses a heuristic to compute the embedding size for each categorical column: 

https://github.com/sajaddarabi/ContrastiveMixup/blob/b3a8ec12cb04f604a30017a960387e33e3b4dabe/model/nn_utils.py#L75 

You could also pass in your own desired embedding size. 

Hope this helps!

**Comment by mortezamg63** [comment]
Hi Sajad,
I really appreciate for your reply. It is clear now. Thanks
